//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp.ScoresService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Grades", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Grades : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int Student_IdField;
        
        private int Course_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Course_NameField;
        
        private decimal GradeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Student_Id {
            get {
                return this.Student_IdField;
            }
            set {
                if ((this.Student_IdField.Equals(value) != true)) {
                    this.Student_IdField = value;
                    this.RaisePropertyChanged("Student_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int Course_Id {
            get {
                return this.Course_IdField;
            }
            set {
                if ((this.Course_IdField.Equals(value) != true)) {
                    this.Course_IdField = value;
                    this.RaisePropertyChanged("Course_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Course_Name {
            get {
                return this.Course_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.Course_NameField, value) != true)) {
                    this.Course_NameField = value;
                    this.RaisePropertyChanged("Course_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public decimal Grade {
            get {
                return this.GradeField;
            }
            set {
                if ((this.GradeField.Equals(value) != true)) {
                    this.GradeField = value;
                    this.RaisePropertyChanged("Grade");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Students", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Students : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ScoresService.WebServiceSoap")]
    public interface WebServiceSoap {
        
        // CODEGEN: Generating message contract since element name GetGradesResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetGrades", ReplyAction="*")]
        WindowsFormsApp.ScoresService.GetGradesResponse GetGrades(WindowsFormsApp.ScoresService.GetGradesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetGrades", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp.ScoresService.GetGradesResponse> GetGradesAsync(WindowsFormsApp.ScoresService.GetGradesRequest request);
        
        // CODEGEN: Generating message contract since element name GetStudentsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStudents", ReplyAction="*")]
        WindowsFormsApp.ScoresService.GetStudentsResponse GetStudents(WindowsFormsApp.ScoresService.GetStudentsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStudents", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp.ScoresService.GetStudentsResponse> GetStudentsAsync(WindowsFormsApp.ScoresService.GetStudentsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetGradesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetGrades", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp.ScoresService.GetGradesRequestBody Body;
        
        public GetGradesRequest() {
        }
        
        public GetGradesRequest(WindowsFormsApp.ScoresService.GetGradesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetGradesRequestBody {
        
        public GetGradesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetGradesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetGradesResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp.ScoresService.GetGradesResponseBody Body;
        
        public GetGradesResponse() {
        }
        
        public GetGradesResponse(WindowsFormsApp.ScoresService.GetGradesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetGradesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WindowsFormsApp.ScoresService.Grades[] GetGradesResult;
        
        public GetGradesResponseBody() {
        }
        
        public GetGradesResponseBody(WindowsFormsApp.ScoresService.Grades[] GetGradesResult) {
            this.GetGradesResult = GetGradesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStudentsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStudents", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp.ScoresService.GetStudentsRequestBody Body;
        
        public GetStudentsRequest() {
        }
        
        public GetStudentsRequest(WindowsFormsApp.ScoresService.GetStudentsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetStudentsRequestBody {
        
        public GetStudentsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStudentsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStudentsResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp.ScoresService.GetStudentsResponseBody Body;
        
        public GetStudentsResponse() {
        }
        
        public GetStudentsResponse(WindowsFormsApp.ScoresService.GetStudentsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetStudentsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WindowsFormsApp.ScoresService.Students[] GetStudentsResult;
        
        public GetStudentsResponseBody() {
        }
        
        public GetStudentsResponseBody(WindowsFormsApp.ScoresService.Students[] GetStudentsResult) {
            this.GetStudentsResult = GetStudentsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : WindowsFormsApp.ScoresService.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<WindowsFormsApp.ScoresService.WebServiceSoap>, WindowsFormsApp.ScoresService.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp.ScoresService.GetGradesResponse WindowsFormsApp.ScoresService.WebServiceSoap.GetGrades(WindowsFormsApp.ScoresService.GetGradesRequest request) {
            return base.Channel.GetGrades(request);
        }
        
        public WindowsFormsApp.ScoresService.Grades[] GetGrades() {
            WindowsFormsApp.ScoresService.GetGradesRequest inValue = new WindowsFormsApp.ScoresService.GetGradesRequest();
            inValue.Body = new WindowsFormsApp.ScoresService.GetGradesRequestBody();
            WindowsFormsApp.ScoresService.GetGradesResponse retVal = ((WindowsFormsApp.ScoresService.WebServiceSoap)(this)).GetGrades(inValue);
            return retVal.Body.GetGradesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp.ScoresService.GetGradesResponse> WindowsFormsApp.ScoresService.WebServiceSoap.GetGradesAsync(WindowsFormsApp.ScoresService.GetGradesRequest request) {
            return base.Channel.GetGradesAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp.ScoresService.GetGradesResponse> GetGradesAsync() {
            WindowsFormsApp.ScoresService.GetGradesRequest inValue = new WindowsFormsApp.ScoresService.GetGradesRequest();
            inValue.Body = new WindowsFormsApp.ScoresService.GetGradesRequestBody();
            return ((WindowsFormsApp.ScoresService.WebServiceSoap)(this)).GetGradesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp.ScoresService.GetStudentsResponse WindowsFormsApp.ScoresService.WebServiceSoap.GetStudents(WindowsFormsApp.ScoresService.GetStudentsRequest request) {
            return base.Channel.GetStudents(request);
        }
        
        public WindowsFormsApp.ScoresService.Students[] GetStudents() {
            WindowsFormsApp.ScoresService.GetStudentsRequest inValue = new WindowsFormsApp.ScoresService.GetStudentsRequest();
            inValue.Body = new WindowsFormsApp.ScoresService.GetStudentsRequestBody();
            WindowsFormsApp.ScoresService.GetStudentsResponse retVal = ((WindowsFormsApp.ScoresService.WebServiceSoap)(this)).GetStudents(inValue);
            return retVal.Body.GetStudentsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp.ScoresService.GetStudentsResponse> WindowsFormsApp.ScoresService.WebServiceSoap.GetStudentsAsync(WindowsFormsApp.ScoresService.GetStudentsRequest request) {
            return base.Channel.GetStudentsAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp.ScoresService.GetStudentsResponse> GetStudentsAsync() {
            WindowsFormsApp.ScoresService.GetStudentsRequest inValue = new WindowsFormsApp.ScoresService.GetStudentsRequest();
            inValue.Body = new WindowsFormsApp.ScoresService.GetStudentsRequestBody();
            return ((WindowsFormsApp.ScoresService.WebServiceSoap)(this)).GetStudentsAsync(inValue);
        }
    }
}
